//
// Created by yuruh on 09/12/16.
//

#ifndef RTYPE_ENTITYTYPE_HPP
#define RTYPE_ENTITYTYPE_HPP

#define BRAINFART_SIZE  10
#define PLAYER_SIZE	5
#define ENNEMY_SIZE 10
#define TAZ_SIZE 10
#define MISSILE_SIZE 2
#define MISSILE_WAVE_SIZE 8

enum EntityType
{
    MONSTERS = 0,
    BRAINFART,
    ENEMY_SHIP,
    TAZ,
    END_MONSTERS = 999,

    DECORATIVE = 1000,
    BACKGROUND_DECORATIVE = 1001,
    WALL,
    END_BACKGROUND_DECORATIVE = 1999,

    FOREGROUND_DECORATIVE = 2000,
    END_FOREGROUND_DECORATIVE = 2999,

    BONUS = 3000,
    SPEED_BONUS,
    END_BONUS = 3999,

    EXPLOSION = 4000,
    SILENT_DEATH,
    END_EXPLOSION = 4999,

    SHOOT = 5000,
    MISSILE,
    MISSILE_WAVE,
    SIDE_MISSILE_2,
    END_SHOOT = 5999,

    PLAYERS = 6000,
    PLAYER1 = 6001,
    PLAYER2 = 6002,
    PLAYER3 = 6003,
    PLAYER4 = 6004,

    UNDEFINED_ENTITY
};

#endif //RTYPE_ENTITYTYPE_HPP
